[package]
name = "py_knocker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
]
